/*
 * File: est_quest_rp.c
 *
 *
 *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
 *
 *   This file is an S-function produced by the S-Function
 *   Builder which only recognizes certain fields.  Changes made
 *   outside these fields will be lost the next time the block is
 *   used to load, edit, and resave this file. This file will be overwritten
 *   by the S-function Builder block. If you want to edit this file by hand,
 *   you must change it only in the area defined as:
 *
 *        %%%-SFUNWIZ_defines_Changes_BEGIN
 *        #define NAME 'replacement text'
 *        %%% SFUNWIZ_defines_Changes_END
 *
 *   DO NOT change NAME--Change the 'replacement text' only.
 *
 *   For better compatibility with the Simulink Coder, the
 *   "wrapper" S-function technique is used.  This is discussed
 *   in the Simulink Coder's Manual in the Chapter titled,
 *   "Wrapper S-functions".
 *
 *  -------------------------------------------------------------------------
 * | See matlabroot/simulink/src/sfuntmpl_doc.c for a more detailed template |
 *  -------------------------------------------------------------------------
 *
 * Created: Mon Jan 26 11:22:94 2026
 */

#define S_FUNCTION_LEVEL               2
#define S_FUNCTION_NAME                est_quest_rp

/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
/* %%%-SFUNWIZ_defines_Changes_BEGIN --- EDIT HERE TO _END */
#define NUM_INPUTS                     2

/* Input Port  0 */
#define IN_PORT_0_NAME                 b_k
#define INPUT_0_DIMS_ND                {3,2}
#define INPUT_0_NUM_ELEMS              6
#define INPUT_0_WIDTH                  3
#define INPUT_DIMS_0_COL               2
#define INPUT_0_DTYPE                  real32_T
#define INPUT_0_COMPLEX                COMPLEX_NO
#define INPUT_0_UNIT                   ""
#define IN_0_BUS_BASED                 0
#define IN_0_BUS_NAME
#define IN_0_DIMS                      2-D
#define INPUT_0_FEEDTHROUGH            1
#define IN_0_ISSIGNED                  1
#define IN_0_WORDLENGTH                8
#define IN_0_FIXPOINTSCALING           1
#define IN_0_FRACTIONLENGTH            3
#define IN_0_BIAS                      0
#define IN_0_SLOPE                     0.125

/* Input Port  1 */
#define IN_PORT_1_NAME                 eci_k
#define INPUT_1_DIMS_ND                {3,2}
#define INPUT_1_NUM_ELEMS              6
#define INPUT_1_WIDTH                  3
#define INPUT_DIMS_1_COL               2
#define INPUT_1_DTYPE                  real32_T
#define INPUT_1_COMPLEX                COMPLEX_NO
#define INPUT_1_UNIT                   ""
#define IN_1_BUS_BASED                 0
#define IN_1_BUS_NAME
#define IN_1_DIMS                      2-D
#define INPUT_1_FEEDTHROUGH            1
#define IN_1_ISSIGNED                  1
#define IN_1_WORDLENGTH                8
#define IN_1_FIXPOINTSCALING           1
#define IN_1_FRACTIONLENGTH            3
#define IN_1_BIAS                      0
#define IN_1_SLOPE                     0.125
#define NUM_OUTPUTS                    3

/* Output Port  0 */
#define OUT_PORT_0_NAME                state_quaternion
#define OUTPUT_0_DIMS_ND               {4,1}
#define OUTPUT_0_NUM_ELEMS             4
#define OUTPUT_0_WIDTH                 4
#define OUTPUT_DIMS_0_COL              1
#define OUTPUT_0_DTYPE                 real32_T
#define OUTPUT_0_COMPLEX               COMPLEX_NO
#define OUTPUT_0_UNIT                  ""
#define OUT_0_BUS_BASED                0
#define OUT_0_BUS_NAME
#define OUT_0_DIMS                     2-D
#define OUT_0_ISSIGNED                 1
#define OUT_0_WORDLENGTH               8
#define OUT_0_FIXPOINTSCALING          1
#define OUT_0_FRACTIONLENGTH           3
#define OUT_0_BIAS                     0
#define OUT_0_SLOPE                    0.125

/* Output Port  1 */
#define OUT_PORT_1_NAME                dcm_out
#define OUTPUT_1_DIMS_ND               {3,3}
#define OUTPUT_1_NUM_ELEMS             9
#define OUTPUT_1_WIDTH                 3
#define OUTPUT_DIMS_1_COL              3
#define OUTPUT_1_DTYPE                 real32_T
#define OUTPUT_1_COMPLEX               COMPLEX_NO
#define OUTPUT_1_UNIT                  ""
#define OUT_1_BUS_BASED                0
#define OUT_1_BUS_NAME
#define OUT_1_DIMS                     2-D
#define OUT_1_ISSIGNED                 1
#define OUT_1_WORDLENGTH               8
#define OUT_1_FIXPOINTSCALING          1
#define OUT_1_FRACTIONLENGTH           3
#define OUT_1_BIAS                     0
#define OUT_1_SLOPE                    0.125

/* Output Port  2 */
#define OUT_PORT_2_NAME                status
#define OUTPUT_2_DIMS_ND               {1,1}
#define OUTPUT_2_NUM_ELEMS             1
#define OUTPUT_2_WIDTH                 1
#define OUTPUT_DIMS_2_COL              1
#define OUTPUT_2_DTYPE                 int32_T
#define OUTPUT_2_COMPLEX               COMPLEX_NO
#define OUTPUT_2_UNIT                  ""
#define OUT_2_BUS_BASED                0
#define OUT_2_BUS_NAME
#define OUT_2_DIMS                     1-D
#define OUT_2_ISSIGNED                 1
#define OUT_2_WORDLENGTH               8
#define OUT_2_FIXPOINTSCALING          1
#define OUT_2_FRACTIONLENGTH           3
#define OUT_2_BIAS                     0
#define OUT_2_SLOPE                    0.125
#define NPARAMS                        0
#define SAMPLE_TIME_0                  0
#define NUM_DISC_STATES                0
#define DISC_STATES_IC                 [0]
#define NUM_CONT_STATES                0
#define CONT_STATES_IC                 [0]
#define SFUNWIZ_GENERATE_TLC           1
#define SOURCEFILES                    "__SFB__SRC_PATH ..\..\..\maxwell_adcs\flight__SFB__INC_PATH ..\..\..\maxwell_adcs\flight\include__SFB__..\..\..\maxwell_adcs\flight\drivers\mtx.c__SFB__..\..\..\maxwell_adcs\flight\tasks\att_det.c__SFB__..\..\..\maxwell_adcs\flight\drivers\global.c__SFB__..\..\..\maxwell_adcs\flight\tasks\conversions.c__SFB__..\..\..\maxwell_adcs\flight\tasks\ref_rotation.c"
#define PANELINDEX                     N/A
#define USE_SIMSTRUCT                  0
#define SHOW_COMPILE_STEPS             1
#define CREATE_DEBUG_MEXFILE           0
#define SAVE_CODE_ONLY                 0
#define SFUNWIZ_REVISION               3.0

/* %%%-SFUNWIZ_defines_Changes_END --- EDIT HERE TO _BEGIN */
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
#include "simstruc.h"

extern void est_quest_rp_Outputs_wrapper(const real32_T *b_k,
  const real32_T *eci_k,
  real32_T *state_quaternion,
  real32_T *dcm_out,
  int32_T *status);

/*=============================*
 * Data Transposition Routines *
 *=============================*/
int linear_idx(const int srcdims[], const int numdims, const int dstk)
{
  int idxCurDim;
  int i, j;
  int srck = 0, dstk_remainingDims = dstk;
  for (i=0,j=numdims-1; i<numdims; i++, j--) {
    idxCurDim = dstk_remainingDims % srcdims[j];
    srck = srck * srcdims[j] + idxCurDim;
    dstk_remainingDims = dstk_remainingDims / srcdims[j];
  }

  return srck;
}

mwSize linear_idxmwsize(const mwSize srcdims[], const int numdims, const mwSize
  dstk)
{
  mwSize idxCurDim;
  int i, j;
  mwSize srck = 0;
  mwSize dstk_remainingDims = dstk;
  for (i=0,j=numdims-1; i<numdims; i++, j--) {
    idxCurDim = dstk_remainingDims % srcdims[j];
    srck = srck * srcdims[j] + idxCurDim;
    dstk_remainingDims = dstk_remainingDims / srcdims[j];
  }

  return srck;
}

/*
   A is [N1xN2xN3] and T is [N3xN2xN1]
   A[n1,n2,n3]=T[n3,n2,n1]

   1) Given linear index k = n1+N1*(n2+N2*n3), find [n1,n2,n3]
   2) Compute corresponding linear index k' = n3+N3*(n2+N2*n1)
   3) Use linear index to assign A[k] = T[k']

   Example input:
   src:     A matrix memory pointer
   srcdims: [N1,N2, N3]
   numdims: 3
   dst:     T matrix memory pointer
   elsize:  sizeof(double)/sizeof(char)
 */
void NDTransposeBySrcSpecs(void *dst, const void *src, const int srcdims[],
  const int numdims, const int elsize)
{
  int w = srcdims[0];
  int k;
  for (k = 1; k < numdims; k ++) {
    w *= srcdims[k];
  }

  for (k = 0; k < w; k ++) {
    int sk = linear_idx(srcdims, numdims, k);
    int offset = k * elsize;
    memcpy((char*)dst + k * elsize, (const char*)src + sk * elsize, elsize);
  }
}

/* the data type of srcdims is mwSize*, the data type in original NDTransposeBySrcSpecs is int* */
void NDTransposeBySrcSpecsMwSize(void *dst, const void *src, const mwSize
  srcdims[], const int numdims, const int elsize)
{
  mwSize w = srcdims[0];
  int k;
  mwSize widthIndex;
  for (k = 1; k < numdims; k ++) {
    w *= srcdims[k];
  }

  for (widthIndex = 0; widthIndex < w; widthIndex ++) {
    mwSize sk = linear_idxmwsize(srcdims, numdims, widthIndex);
    memcpy((char*)dst + widthIndex * elsize, (const char*)src + sk * elsize,
           elsize);
  }
}

void NDTransposeByDstSpecs(void *dst, const void *src, const int dstdims[],
  const int numdims, const int elsize)
{
  int w = dstdims[0];
  int k;
  for (k = 1; k < numdims; k ++) {
    w *= dstdims[k];
  }

  for (k = 0; k < w; k ++) {
    int dk = linear_idx(dstdims, numdims, k);
    int offset = k * elsize;
    memcpy((char*)dst + dk * elsize, (const char*)src + k * elsize, elsize);
  }
}

/*====================*
 * S-function methods *
 *====================*/
/* Function: mdlInitializeSizes ===============================================
 * Abstract:
 *   Setup sizes of the various vectors.
 */
static void mdlInitializeSizes(SimStruct *S)
{
  DECL_AND_INIT_DIMSINFO(inputDimsInfo);
  DECL_AND_INIT_DIMSINFO(outputDimsInfo);
  ssSetNumSFcnParams(S, NPARAMS);
  if (ssGetNumSFcnParams(S) != ssGetSFcnParamsCount(S)) {
    return;                            /* Parameter mismatch will be reported by Simulink */
  }

  ssSetArrayLayoutForCodeGen(S, SS_ROW_MAJOR);
  ssSetOperatingPointCompliance(S, USE_DEFAULT_OPERATING_POINT);
  ssSetNumContStates(S, NUM_CONT_STATES);
  ssSetNumDiscStates(S, NUM_DISC_STATES);
  if (!ssSetNumInputPorts(S, NUM_INPUTS))
    return;

  /* Input Port 0 */
  ssAllowSignalsWithMoreThan2D(S);
  inputDimsInfo.numDims = 2;
  inputDimsInfo.width = INPUT_0_NUM_ELEMS;
  int_T in0Dims[] = INPUT_0_DIMS_ND;
  inputDimsInfo.dims = in0Dims;
  ssSetInputPortDimensionInfo(S, 0, &inputDimsInfo);
  ssSetInputPortDataType(S, 0, SS_SINGLE);
  ssSetInputPortComplexSignal(S, 0, INPUT_0_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 0, INPUT_0_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 0, 1);/*direct input signal access*/

  /* Input Port 1 */
  inputDimsInfo.numDims = 2;
  inputDimsInfo.width = INPUT_1_NUM_ELEMS;
  int_T in1Dims[] = INPUT_1_DIMS_ND;
  inputDimsInfo.dims = in1Dims;
  ssSetInputPortDimensionInfo(S, 1, &inputDimsInfo);
  ssSetInputPortDataType(S, 1, SS_SINGLE);
  ssSetInputPortComplexSignal(S, 1, INPUT_1_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 1, INPUT_1_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 1, 1);/*direct input signal access*/

  /*
   * Configure the Units for Input Ports
   */
  if (ssGetSimMode(S) != SS_SIMMODE_SIZES_CALL_ONLY) {

#if defined(MATLAB_MEX_FILE)

    UnitId inUnitIdReg;
    ssRegisterUnitFromExpr(S, INPUT_0_UNIT, &inUnitIdReg);
    if (inUnitIdReg != INVALID_UNIT_ID) {
      ssSetInputPortUnit(S, 0, inUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for input port b_k of S-Function est_quest_rp");
      return;
    }

    ssRegisterUnitFromExpr(S, INPUT_1_UNIT, &inUnitIdReg);
    if (inUnitIdReg != INVALID_UNIT_ID) {
      ssSetInputPortUnit(S, 1, inUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for input port eci_k of S-Function est_quest_rp");
      return;
    }

#endif

  }

  if (!ssSetNumOutputPorts(S, NUM_OUTPUTS))
    return;

  /* Output Port 0 */
  outputDimsInfo.numDims = 2;
  outputDimsInfo.width = OUTPUT_0_NUM_ELEMS;
  int_T out0Dims[] = OUTPUT_0_DIMS_ND;
  outputDimsInfo.dims = out0Dims;
  ssSetOutputPortDimensionInfo(S, 0, &outputDimsInfo);
  ssSetOutputPortDataType(S, 0, SS_SINGLE);
  ssSetOutputPortComplexSignal(S, 0, OUTPUT_0_COMPLEX);

  /* Output Port 1 */
  outputDimsInfo.numDims = 2;
  outputDimsInfo.width = OUTPUT_1_NUM_ELEMS;
  int_T out1Dims[] = OUTPUT_1_DIMS_ND;
  outputDimsInfo.dims = out1Dims;
  ssSetOutputPortDimensionInfo(S, 1, &outputDimsInfo);
  ssSetOutputPortDataType(S, 1, SS_SINGLE);
  ssSetOutputPortComplexSignal(S, 1, OUTPUT_1_COMPLEX);

  /* Output Port 2 */
  ssSetOutputPortWidth(S, 2, OUTPUT_2_NUM_ELEMS);
  ssSetOutputPortDataType(S, 2, SS_INT32);
  ssSetOutputPortComplexSignal(S, 2, OUTPUT_2_COMPLEX);

  /*
   * Configure the Units for Output Ports
   */
  if (ssGetSimMode(S) != SS_SIMMODE_SIZES_CALL_ONLY) {

#if defined(MATLAB_MEX_FILE)

    UnitId outUnitIdReg;
    ssRegisterUnitFromExpr(S, OUTPUT_0_UNIT, &outUnitIdReg);
    if (outUnitIdReg != INVALID_UNIT_ID) {
      ssSetOutputPortUnit(S, 0, outUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for output port state_quaternion of S-Function est_quest_rp");
      return;
    }

    ssRegisterUnitFromExpr(S, OUTPUT_1_UNIT, &outUnitIdReg);
    if (outUnitIdReg != INVALID_UNIT_ID) {
      ssSetOutputPortUnit(S, 1, outUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for output port dcm_out of S-Function est_quest_rp");
      return;
    }

    ssRegisterUnitFromExpr(S, OUTPUT_2_UNIT, &outUnitIdReg);
    if (outUnitIdReg != INVALID_UNIT_ID) {
      ssSetOutputPortUnit(S, 2, outUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for output port status of S-Function est_quest_rp");
      return;
    }

#endif

  }

  if (!ssSetNumDWork(S, 5))
    return;

  /*
   * Configure the dwork 0 (b_k_t)
   */
  ssSetDWorkDataType(S, 0, ssGetInputPortDataType(S, 0));
  ssSetDWorkUsageType(S, 0, SS_DWORK_USED_AS_SCRATCH);
  ssSetDWorkName(S, 0, "b_k_t");
  ssSetDWorkWidth(S, 0, ssGetInputPortWidth(S, 0));
  ssSetDWorkComplexSignal(S, 0, COMPLEX_NO);

  /*
   * Configure the dwork 1 (eci_k_t)
   */
  ssSetDWorkDataType(S, 1, ssGetInputPortDataType(S, 1));
  ssSetDWorkUsageType(S, 1, SS_DWORK_USED_AS_SCRATCH);
  ssSetDWorkName(S, 1, "eci_k_t");
  ssSetDWorkWidth(S, 1, ssGetInputPortWidth(S, 1));
  ssSetDWorkComplexSignal(S, 1, COMPLEX_NO);

  /*
   * Configure the dwork 2 (state_quaternion_t)
   */
  ssSetDWorkDataType(S, 2, ssGetOutputPortDataType(S, 0));
  ssSetDWorkUsageType(S, 2, SS_DWORK_USED_AS_SCRATCH);
  ssSetDWorkName(S, 2, "state_quaternion_t");
  ssSetDWorkWidth(S, 2, ssGetOutputPortWidth(S, 0));
  ssSetDWorkComplexSignal(S, 2, COMPLEX_NO);

  /*
   * Configure the dwork 3 (dcm_out_t)
   */
  ssSetDWorkDataType(S, 3, ssGetOutputPortDataType(S, 1));
  ssSetDWorkUsageType(S, 3, SS_DWORK_USED_AS_SCRATCH);
  ssSetDWorkName(S, 3, "dcm_out_t");
  ssSetDWorkWidth(S, 3, ssGetOutputPortWidth(S, 1));
  ssSetDWorkComplexSignal(S, 3, COMPLEX_NO);

  /*
   * Configure the dwork 4 (status_t)
   */
  ssSetDWorkDataType(S, 4, ssGetOutputPortDataType(S, 2));
  ssSetDWorkUsageType(S, 4, SS_DWORK_USED_AS_SCRATCH);
  ssSetDWorkName(S, 4, "status_t");
  ssSetDWorkWidth(S, 4, ssGetOutputPortWidth(S, 2));
  ssSetDWorkComplexSignal(S, 4, COMPLEX_NO);
  ssSetNumPWork(S, 0);
  ssSetNumSampleTimes(S, 1);
  ssSetNumRWork(S, 0);
  ssSetNumIWork(S, 0);
  ssSetNumModes(S, 0);
  ssSetNumNonsampledZCs(S, 0);
  ssSetSimulinkVersionGeneratedIn(S, "25.2");

  /* Take care when specifying exception free code - see sfuntmpl_doc.c */
  ssSetRuntimeThreadSafetyCompliance(S, RUNTIME_THREAD_SAFETY_COMPLIANCE_FALSE);
  ssSetOptions(S, (SS_OPTION_EXCEPTION_FREE_CODE |
                   SS_OPTION_WORKS_WITH_CODE_REUSE));
  ssSupportsMultipleExecInstances(S, true);
}

#if defined(MATLAB_MEX_FILE)
#define MDL_SET_INPUT_PORT_DIMENSION_INFO

static void mdlSetInputPortDimensionInfo(SimStruct *S,
  int_T port,
  const DimsInfo_T *dimsInfo)
{
  if (!ssSetInputPortDimensionInfo(S, port, dimsInfo))
    return;
}

#endif

#define MDL_SET_OUTPUT_PORT_DIMENSION_INFO
#if defined(MDL_SET_OUTPUT_PORT_DIMENSION_INFO)

static void mdlSetOutputPortDimensionInfo(SimStruct *S,
  int_T port,
  const DimsInfo_T *dimsInfo)
{
  if (!ssSetOutputPortDimensionInfo(S, port, dimsInfo))
    return;
}

#endif

#define MDL_SET_DEFAULT_PORT_DIMENSION_INFO

static void mdlSetDefaultPortDimensionInfo(SimStruct *S)
{
  DECL_AND_INIT_DIMSINFO(portDimsInfo);
  int_T dims[2];

  /* Setting default dimensions for input port 0 */
  portDimsInfo.width = INPUT_0_NUM_ELEMS;
  dims[0] = INPUT_0_NUM_ELEMS;
  dims[1] = 1;
  portDimsInfo.dims = dims;
  portDimsInfo.numDims = 2;
  if (ssGetInputPortWidth(S, 0) == DYNAMICALLY_SIZED) {
    ssSetInputPortMatrixDimensions(S, 0, 1 , 1);
  }

  /* Setting default dimensions for input port 1 */
  portDimsInfo.width = INPUT_1_NUM_ELEMS;
  dims[0] = INPUT_1_NUM_ELEMS;
  dims[1] = 1;
  portDimsInfo.dims = dims;
  portDimsInfo.numDims = 2;
  if (ssGetInputPortWidth(S, 1) == DYNAMICALLY_SIZED) {
    ssSetInputPortMatrixDimensions(S, 1, 1 , 1);
  }

  /* Setting default dimensions for output port 0 */
  portDimsInfo.width = OUTPUT_0_NUM_ELEMS;
  dims[0] = OUTPUT_0_NUM_ELEMS;
  dims[1] = 1;
  portDimsInfo.numDims = 2;
  if (ssGetOutputPortNumDimensions(S, 0) == (-1)) {
    ssSetOutputPortDimensionInfo(S, 0, &portDimsInfo);
  }

  /* Setting default dimensions for output port 1 */
  portDimsInfo.width = OUTPUT_1_NUM_ELEMS;
  dims[0] = OUTPUT_1_NUM_ELEMS;
  dims[1] = 1;
  portDimsInfo.numDims = 2;
  if (ssGetOutputPortNumDimensions(S, 1) == (-1)) {
    ssSetOutputPortDimensionInfo(S, 1, &portDimsInfo);
  }

  return;
}

/* Function: mdlInitializeSampleTimes =========================================
 * Abstract:
 *    Specifiy  the sample time.
 */
static void mdlInitializeSampleTimes(SimStruct *S)
{
  ssSetSampleTime(S, 0, SAMPLE_TIME_0);
  ssSetModelReferenceSampleTimeDefaultInheritance(S);
  ssSetOffsetTime(S, 0, 0.0);
}

#define MDL_SET_INPUT_PORT_DATA_TYPE

static void mdlSetInputPortDataType(SimStruct *S, int port, DTypeId dType)
{
  ssSetInputPortDataType(S, 0, dType);
}

#define MDL_SET_OUTPUT_PORT_DATA_TYPE

static void mdlSetOutputPortDataType(SimStruct *S, int port, DTypeId dType)
{
  ssSetOutputPortDataType(S, 0, dType);
}

#define MDL_SET_DEFAULT_PORT_DATA_TYPES

static void mdlSetDefaultPortDataTypes(SimStruct *S)
{
  ssSetInputPortDataType(S, 0, SS_DOUBLE);
  ssSetOutputPortDataType(S, 0, SS_DOUBLE);
}

#define MDL_START                                                /* Change to #undef to remove function */
#if defined(MDL_START)

/* Function: mdlStart =======================================================
 * Abstract:
 *    This function is called once at start of model execution. If you
 *    have states that should be initialized once, this is the place
 *    to do it.
 */
static void mdlStart(SimStruct *S)
{
}

#endif                                 /*  MDL_START */

/* Function: mdlOutputs =======================================================
 *
 */
static void mdlOutputs(SimStruct *S, int_T tid)
{
  const real32_T *b_k = (real32_T *) ssGetInputPortRealSignal(S, 0);
  const real32_T *eci_k = (real32_T *) ssGetInputPortRealSignal(S, 1);
  real32_T *state_quaternion = (real32_T *) ssGetOutputPortRealSignal(S, 0);
  real32_T *dcm_out = (real32_T *) ssGetOutputPortRealSignal(S, 1);
  int32_T *status = (int32_T *) ssGetOutputPortRealSignal(S, 2);

  /* S-Function Builder Row Major Support has been enabled for custom
   * code, a transposed copy will be created for any array signals.
   */
  real32_T *b_k_t = (real32_T *)ssGetDWork(S, 0);
  real32_T *eci_k_t = (real32_T *)ssGetDWork(S, 1);
  real32_T *state_quaternion_t = (real32_T *)ssGetDWork(S, 2);
  real32_T *dcm_out_t = (real32_T *)ssGetDWork(S, 3);
  int32_T *status_t = (int32_T *)ssGetDWork(S, 4);
  NDTransposeBySrcSpecs((void*)b_k_t, (const void*)b_k, ssGetInputPortDimensions
                        (S, 0), ssGetInputPortNumDimensions(S, 0), sizeof
                        (real32_T));
  NDTransposeBySrcSpecs((void*)eci_k_t, (const void*)eci_k,
                        ssGetInputPortDimensions(S, 1),
                        ssGetInputPortNumDimensions(S, 1), sizeof(real32_T));
  est_quest_rp_Outputs_wrapper(b_k_t, eci_k_t, state_quaternion_t, dcm_out_t,
    status_t);
  NDTransposeByDstSpecs((void*)state_quaternion, (const void*)state_quaternion_t,
                        ssGetOutputPortDimensions(S, 0),
                        ssGetOutputPortNumDimensions(S, 0), sizeof(real32_T));
  NDTransposeByDstSpecs((void*)dcm_out, (const void*)dcm_out_t,
                        ssGetOutputPortDimensions(S, 1),
                        ssGetOutputPortNumDimensions(S, 1), sizeof(real32_T));
  NDTransposeByDstSpecs((void*)status, (const void*)status_t,
                        ssGetOutputPortDimensions(S, 2),
                        ssGetOutputPortNumDimensions(S, 2), sizeof(int32_T));
}

/* Function: mdlTerminate =====================================================
 * Abstract:
 *    In this function, you should perform any actions that are necessary
 *    at the termination of a simulation.  For example, if memory was
 *    allocated in mdlStart, this is the place to free it.
 */
static void mdlTerminate(SimStruct *S)
{
}

#ifdef MATLAB_MEX_FILE                 /* Is this file being compiled as a MEX-file? */
#include "simulink.c"                  /* MEX-file interface mechanism */
#else
#include "cg_sfun.h"                   /* Code generation registration function */
#endif
