/*
 * File: gs_angle_distance.c
 *
 *
 *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
 *
 *   This file is an S-function produced by the S-Function
 *   Builder which only recognizes certain fields.  Changes made
 *   outside these fields will be lost the next time the block is
 *   used to load, edit, and resave this file. This file will be overwritten
 *   by the S-function Builder block. If you want to edit this file by hand,
 *   you must change it only in the area defined as:
 *
 *        %%%-SFUNWIZ_defines_Changes_BEGIN
 *        #define NAME 'replacement text'
 *        %%% SFUNWIZ_defines_Changes_END
 *
 *   DO NOT change NAME--Change the 'replacement text' only.
 *
 *   For better compatibility with the Simulink Coder, the
 *   "wrapper" S-function technique is used.  This is discussed
 *   in the Simulink Coder's Manual in the Chapter titled,
 *   "Wrapper S-functions".
 *
 *  -------------------------------------------------------------------------
 * | See matlabroot/simulink/src/sfuntmpl_doc.c for a more detailed template |
 *  -------------------------------------------------------------------------
 *
 * Created: Fri Oct 31 13:31:42 2025
 */

#define S_FUNCTION_LEVEL               2
#define S_FUNCTION_NAME                gs_angle_distance

/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
/* %%%-SFUNWIZ_defines_Changes_BEGIN --- EDIT HERE TO _END */
#define NUM_INPUTS                     3

/* Input Port  0 */
#define IN_PORT_0_NAME                 sc_pos_vec_ecef
#define INPUT_0_DIMS_ND                {1,1}
#define INPUT_0_NUM_ELEMS              1
#define INPUT_0_WIDTH                  1
#define INPUT_DIMS_0_COL               1
#define INPUT_0_DTYPE                  real32_T
#define INPUT_0_COMPLEX                COMPLEX_NO
#define INPUT_0_UNIT                   ""
#define IN_0_BUS_BASED                 0
#define IN_0_BUS_NAME
#define IN_0_DIMS                      1-D
#define INPUT_0_FEEDTHROUGH            1
#define IN_0_ISSIGNED                  1
#define IN_0_WORDLENGTH                8
#define IN_0_FIXPOINTSCALING           1
#define IN_0_FRACTIONLENGTH            3
#define IN_0_BIAS                      0
#define IN_0_SLOPE                     0.125

/* Input Port  1 */
#define IN_PORT_1_NAME                 gnd_stn_pos_vec_ecef
#define INPUT_1_DIMS_ND                {1,1}
#define INPUT_1_NUM_ELEMS              1
#define INPUT_1_WIDTH                  1
#define INPUT_DIMS_1_COL               1
#define INPUT_1_DTYPE                  real32_T
#define INPUT_1_COMPLEX                COMPLEX_NO
#define INPUT_1_UNIT                   ""
#define IN_1_BUS_BASED                 0
#define IN_1_BUS_NAME
#define IN_1_DIMS                      1-D
#define INPUT_1_FEEDTHROUGH            1
#define IN_1_ISSIGNED                  1
#define IN_1_WORDLENGTH                8
#define IN_1_FIXPOINTSCALING           1
#define IN_1_FRACTIONLENGTH            3
#define IN_1_BIAS                      0
#define IN_1_SLOPE                     0.125

/* Input Port  2 */
#define IN_PORT_2_NAME                 angle
#define INPUT_2_DIMS_ND                {1,1}
#define INPUT_2_NUM_ELEMS              1
#define INPUT_2_WIDTH                  1
#define INPUT_DIMS_2_COL               1
#define INPUT_2_DTYPE                  real32_T
#define INPUT_2_COMPLEX                COMPLEX_NO
#define INPUT_2_UNIT                   ""
#define IN_2_BUS_BASED                 0
#define IN_2_BUS_NAME
#define IN_2_DIMS                      1-D
#define INPUT_2_FEEDTHROUGH            1
#define IN_2_ISSIGNED                  1
#define IN_2_WORDLENGTH                8
#define IN_2_FIXPOINTSCALING           1
#define IN_2_FRACTIONLENGTH            3
#define IN_2_BIAS                      0
#define IN_2_SLOPE                     0.125
#define NUM_OUTPUTS                    1

/* Output Port  0 */
#define OUT_PORT_0_NAME                distance
#define OUTPUT_0_DIMS_ND               {1,1}
#define OUTPUT_0_NUM_ELEMS             1
#define OUTPUT_0_WIDTH                 1
#define OUTPUT_DIMS_0_COL              1
#define OUTPUT_0_DTYPE                 real32_T
#define OUTPUT_0_COMPLEX               COMPLEX_NO
#define OUTPUT_0_UNIT                  ""
#define OUT_0_BUS_BASED                0
#define OUT_0_BUS_NAME
#define OUT_0_DIMS                     1-D
#define OUT_0_ISSIGNED                 1
#define OUT_0_WORDLENGTH               8
#define OUT_0_FIXPOINTSCALING          1
#define OUT_0_FRACTIONLENGTH           3
#define OUT_0_BIAS                     0
#define OUT_0_SLOPE                    0.125
#define NPARAMS                        0
#define SAMPLE_TIME_0                  INHERITED_SAMPLE_TIME
#define NUM_DISC_STATES                0
#define DISC_STATES_IC                 [0]
#define NUM_CONT_STATES                0
#define CONT_STATES_IC                 [0]
#define SFUNWIZ_GENERATE_TLC           1
#define SOURCEFILES                    "__SFB__SRC_PATH ..\..\..\maxwell_adcs\flight__SFB__INC_PATH ..\..\..\maxwell_adcs\flight\include__SFB__..\..\..\maxwell_adcs\flight\drivers\mtx.c__SFB__..\..\..\maxwell_adcs\flight\tasks\conversions.c__SFB__..\..\..\maxwell_adcs\flight\tasks\ref_rotation.c__SFB__..\..\..\maxwell_adcs\flight\tasks\att_det.c__SFB__..\..\..\maxwell_adcs\flight\drivers\global.c__SFB__"
#define PANELINDEX                     N/A
#define USE_SIMSTRUCT                  0
#define SHOW_COMPILE_STEPS             0
#define CREATE_DEBUG_MEXFILE           0
#define SAVE_CODE_ONLY                 0
#define SFUNWIZ_REVISION               3.0

/* %%%-SFUNWIZ_defines_Changes_END --- EDIT HERE TO _BEGIN */
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
#include "simstruc.h"

extern void gs_angle_distance_Outputs_wrapper(const real32_T *sc_pos_vec_ecef,
  const real32_T *gnd_stn_pos_vec_ecef,
  const real32_T *angle,
  real32_T *distance);

/*=============================*
 * Data Transposition Routines *
 *=============================*/
int linear_idx(const int srcdims[], const int numdims, const int dstk)
{
  int idxCurDim;
  int i, j;
  int srck = 0, dstk_remainingDims = dstk;
  for (i=0,j=numdims-1; i<numdims; i++, j--) {
    idxCurDim = dstk_remainingDims % srcdims[j];
    srck = srck * srcdims[j] + idxCurDim;
    dstk_remainingDims = dstk_remainingDims / srcdims[j];
  }

  return srck;
}

mwSize linear_idxmwsize(const mwSize srcdims[], const int numdims, const mwSize
  dstk)
{
  mwSize idxCurDim;
  int i, j;
  mwSize srck = 0;
  mwSize dstk_remainingDims = dstk;
  for (i=0,j=numdims-1; i<numdims; i++, j--) {
    idxCurDim = dstk_remainingDims % srcdims[j];
    srck = srck * srcdims[j] + idxCurDim;
    dstk_remainingDims = dstk_remainingDims / srcdims[j];
  }

  return srck;
}

/*
   A is [N1xN2xN3] and T is [N3xN2xN1]
   A[n1,n2,n3]=T[n3,n2,n1]

   1) Given linear index k = n1+N1*(n2+N2*n3), find [n1,n2,n3]
   2) Compute corresponding linear index k' = n3+N3*(n2+N2*n1)
   3) Use linear index to assign A[k] = T[k']

   Example input:
   src:     A matrix memory pointer
   srcdims: [N1,N2, N3]
   numdims: 3
   dst:     T matrix memory pointer
   elsize:  sizeof(double)/sizeof(char)
 */
void NDTransposeBySrcSpecs(void *dst, const void *src, const int srcdims[],
  const int numdims, const int elsize)
{
  int w = srcdims[0];
  int k;
  for (k = 1; k < numdims; k ++) {
    w *= srcdims[k];
  }

  for (k = 0; k < w; k ++) {
    int sk = linear_idx(srcdims, numdims, k);
    int offset = k * elsize;
    memcpy((char*)dst + k * elsize, (const char*)src + sk * elsize, elsize);
  }
}

/* the data type of srcdims is mwSize*, the data type in original NDTransposeBySrcSpecs is int* */
void NDTransposeBySrcSpecsMwSize(void *dst, const void *src, const mwSize
  srcdims[], const int numdims, const int elsize)
{
  mwSize w = srcdims[0];
  int k;
  mwSize widthIndex;
  for (k = 1; k < numdims; k ++) {
    w *= srcdims[k];
  }

  for (widthIndex = 0; widthIndex < w; widthIndex ++) {
    mwSize sk = linear_idxmwsize(srcdims, numdims, widthIndex);
    memcpy((char*)dst + widthIndex * elsize, (const char*)src + sk * elsize,
           elsize);
  }
}

void NDTransposeByDstSpecs(void *dst, const void *src, const int dstdims[],
  const int numdims, const int elsize)
{
  int w = dstdims[0];
  int k;
  for (k = 1; k < numdims; k ++) {
    w *= dstdims[k];
  }

  for (k = 0; k < w; k ++) {
    int dk = linear_idx(dstdims, numdims, k);
    int offset = k * elsize;
    memcpy((char*)dst + dk * elsize, (const char*)src + k * elsize, elsize);
  }
}

/*====================*
 * S-function methods *
 *====================*/
/* Function: mdlInitializeSizes ===============================================
 * Abstract:
 *   Setup sizes of the various vectors.
 */
static void mdlInitializeSizes(SimStruct *S)
{
  ssSetNumSFcnParams(S, NPARAMS);
  if (ssGetNumSFcnParams(S) != ssGetSFcnParamsCount(S)) {
    return;                            /* Parameter mismatch will be reported by Simulink */
  }

  ssSetArrayLayoutForCodeGen(S, SS_ROW_MAJOR);
  ssSetOperatingPointCompliance(S, USE_DEFAULT_OPERATING_POINT);
  ssSetNumContStates(S, NUM_CONT_STATES);
  ssSetNumDiscStates(S, NUM_DISC_STATES);
  if (!ssSetNumInputPorts(S, NUM_INPUTS))
    return;

  /* Input Port 0 */
  ssSetInputPortWidth(S, 0, INPUT_0_NUM_ELEMS);
  ssSetInputPortDataType(S, 0, SS_SINGLE);
  ssSetInputPortComplexSignal(S, 0, INPUT_0_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 0, INPUT_0_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 0, 1);/*direct input signal access*/

  /* Input Port 1 */
  ssSetInputPortWidth(S, 1, INPUT_1_NUM_ELEMS);
  ssSetInputPortDataType(S, 1, SS_SINGLE);
  ssSetInputPortComplexSignal(S, 1, INPUT_1_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 1, INPUT_1_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 1, 1);/*direct input signal access*/

  /* Input Port 2 */
  ssSetInputPortWidth(S, 2, INPUT_2_NUM_ELEMS);
  ssSetInputPortDataType(S, 2, SS_SINGLE);
  ssSetInputPortComplexSignal(S, 2, INPUT_2_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 2, INPUT_2_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 2, 1);/*direct input signal access*/

  /*
   * Configure the Units for Input Ports
   */
  if (ssGetSimMode(S) != SS_SIMMODE_SIZES_CALL_ONLY) {

#if defined(MATLAB_MEX_FILE)

    UnitId inUnitIdReg;
    ssRegisterUnitFromExpr(S, INPUT_0_UNIT, &inUnitIdReg);
    if (inUnitIdReg != INVALID_UNIT_ID) {
      ssSetInputPortUnit(S, 0, inUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for input port sc_pos_vec_ecef of S-Function gs_angle_distance");
      return;
    }

    ssRegisterUnitFromExpr(S, INPUT_1_UNIT, &inUnitIdReg);
    if (inUnitIdReg != INVALID_UNIT_ID) {
      ssSetInputPortUnit(S, 1, inUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for input port gnd_stn_pos_vec_ecef of S-Function gs_angle_distance");
      return;
    }

    ssRegisterUnitFromExpr(S, INPUT_2_UNIT, &inUnitIdReg);
    if (inUnitIdReg != INVALID_UNIT_ID) {
      ssSetInputPortUnit(S, 2, inUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for input port angle of S-Function gs_angle_distance");
      return;
    }

#endif

  }

  if (!ssSetNumOutputPorts(S, NUM_OUTPUTS))
    return;

  /* Output Port 0 */
  ssSetOutputPortWidth(S, 0, OUTPUT_0_NUM_ELEMS);
  ssSetOutputPortDataType(S, 0, SS_SINGLE);
  ssSetOutputPortComplexSignal(S, 0, OUTPUT_0_COMPLEX);

  /*
   * Configure the Units for Output Ports
   */
  if (ssGetSimMode(S) != SS_SIMMODE_SIZES_CALL_ONLY) {

#if defined(MATLAB_MEX_FILE)

    UnitId outUnitIdReg;
    ssRegisterUnitFromExpr(S, OUTPUT_0_UNIT, &outUnitIdReg);
    if (outUnitIdReg != INVALID_UNIT_ID) {
      ssSetOutputPortUnit(S, 0, outUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for output port distance of S-Function gs_angle_distance");
      return;
    }

#endif

  }

  if (!ssSetNumDWork(S, 4))
    return;

  /*
   * Configure the dwork 0 (sc_pos_vec_ecef_t)
   */
  ssSetDWorkDataType(S, 0, ssGetInputPortDataType(S, 0));
  ssSetDWorkUsageType(S, 0, SS_DWORK_USED_AS_SCRATCH);
  ssSetDWorkName(S, 0, "sc_pos_vec_ecef_t");
  ssSetDWorkWidth(S, 0, ssGetInputPortWidth(S, 0));
  ssSetDWorkComplexSignal(S, 0, COMPLEX_NO);

  /*
   * Configure the dwork 1 (gnd_stn_pos_vec_ecef_t)
   */
  ssSetDWorkDataType(S, 1, ssGetInputPortDataType(S, 1));
  ssSetDWorkUsageType(S, 1, SS_DWORK_USED_AS_SCRATCH);
  ssSetDWorkName(S, 1, "gnd_stn_pos_vec_ecef_t");
  ssSetDWorkWidth(S, 1, ssGetInputPortWidth(S, 1));
  ssSetDWorkComplexSignal(S, 1, COMPLEX_NO);

  /*
   * Configure the dwork 2 (angle_t)
   */
  ssSetDWorkDataType(S, 2, ssGetInputPortDataType(S, 2));
  ssSetDWorkUsageType(S, 2, SS_DWORK_USED_AS_SCRATCH);
  ssSetDWorkName(S, 2, "angle_t");
  ssSetDWorkWidth(S, 2, ssGetInputPortWidth(S, 2));
  ssSetDWorkComplexSignal(S, 2, COMPLEX_NO);

  /*
   * Configure the dwork 3 (distance_t)
   */
  ssSetDWorkDataType(S, 3, ssGetOutputPortDataType(S, 0));
  ssSetDWorkUsageType(S, 3, SS_DWORK_USED_AS_SCRATCH);
  ssSetDWorkName(S, 3, "distance_t");
  ssSetDWorkWidth(S, 3, ssGetOutputPortWidth(S, 0));
  ssSetDWorkComplexSignal(S, 3, COMPLEX_NO);
  ssSetNumPWork(S, 0);
  ssSetNumSampleTimes(S, 1);
  ssSetNumRWork(S, 0);
  ssSetNumIWork(S, 0);
  ssSetNumModes(S, 0);
  ssSetNumNonsampledZCs(S, 0);
  ssSetSimulinkVersionGeneratedIn(S, "25.2");

  /* Take care when specifying exception free code - see sfuntmpl_doc.c */
  ssSetRuntimeThreadSafetyCompliance(S, RUNTIME_THREAD_SAFETY_COMPLIANCE_FALSE);
  ssSetOptions(S, (SS_OPTION_EXCEPTION_FREE_CODE |
                   SS_OPTION_WORKS_WITH_CODE_REUSE));
  ssSupportsMultipleExecInstances(S, true);
}

#if defined(MATLAB_MEX_FILE)
#define MDL_SET_INPUT_PORT_DIMENSION_INFO

static void mdlSetInputPortDimensionInfo(SimStruct *S,
  int_T port,
  const DimsInfo_T *dimsInfo)
{
  if (!ssSetInputPortDimensionInfo(S, port, dimsInfo))
    return;
}

#endif

#define MDL_SET_OUTPUT_PORT_DIMENSION_INFO
#if defined(MDL_SET_OUTPUT_PORT_DIMENSION_INFO)

static void mdlSetOutputPortDimensionInfo(SimStruct *S,
  int_T port,
  const DimsInfo_T *dimsInfo)
{
  if (!ssSetOutputPortDimensionInfo(S, port, dimsInfo))
    return;
}

#endif

/* Function: mdlInitializeSampleTimes =========================================
 * Abstract:
 *    Specifiy  the sample time.
 */
static void mdlInitializeSampleTimes(SimStruct *S)
{
  ssSetSampleTime(S, 0, SAMPLE_TIME_0);
  ssSetModelReferenceSampleTimeDefaultInheritance(S);
  ssSetOffsetTime(S, 0, 0.0);
}

#define MDL_SET_INPUT_PORT_DATA_TYPE

static void mdlSetInputPortDataType(SimStruct *S, int port, DTypeId dType)
{
  ssSetInputPortDataType(S, 0, dType);
}

#define MDL_SET_OUTPUT_PORT_DATA_TYPE

static void mdlSetOutputPortDataType(SimStruct *S, int port, DTypeId dType)
{
  ssSetOutputPortDataType(S, 0, dType);
}

#define MDL_SET_DEFAULT_PORT_DATA_TYPES

static void mdlSetDefaultPortDataTypes(SimStruct *S)
{
  ssSetInputPortDataType(S, 0, SS_DOUBLE);
  ssSetOutputPortDataType(S, 0, SS_DOUBLE);
}

#define MDL_START                                                /* Change to #undef to remove function */
#if defined(MDL_START)

/* Function: mdlStart =======================================================
 * Abstract:
 *    This function is called once at start of model execution. If you
 *    have states that should be initialized once, this is the place
 *    to do it.
 */
static void mdlStart(SimStruct *S)
{
}

#endif                                 /*  MDL_START */

/* Function: mdlOutputs =======================================================
 *
 */
static void mdlOutputs(SimStruct *S, int_T tid)
{
  const real32_T *sc_pos_vec_ecef = (real32_T *) ssGetInputPortRealSignal(S, 0);
  const real32_T *gnd_stn_pos_vec_ecef = (real32_T *) ssGetInputPortRealSignal(S,
    1);
  const real32_T *angle = (real32_T *) ssGetInputPortRealSignal(S, 2);
  real32_T *distance = (real32_T *) ssGetOutputPortRealSignal(S, 0);

  /* S-Function Builder Row Major Support has been enabled for custom
   * code, a transposed copy will be created for any array signals.
   */
  real32_T *sc_pos_vec_ecef_t = (real32_T *)ssGetDWork(S, 0);
  real32_T *gnd_stn_pos_vec_ecef_t = (real32_T *)ssGetDWork(S, 1);
  real32_T *angle_t = (real32_T *)ssGetDWork(S, 2);
  real32_T *distance_t = (real32_T *)ssGetDWork(S, 3);
  NDTransposeBySrcSpecs((void*)sc_pos_vec_ecef_t, (const void*)sc_pos_vec_ecef,
                        ssGetInputPortDimensions(S, 0),
                        ssGetInputPortNumDimensions(S, 0), sizeof(real32_T));
  NDTransposeBySrcSpecs((void*)gnd_stn_pos_vec_ecef_t, (const void*)
                        gnd_stn_pos_vec_ecef, ssGetInputPortDimensions(S, 1),
                        ssGetInputPortNumDimensions(S, 1), sizeof(real32_T));
  NDTransposeBySrcSpecs((void*)angle_t, (const void*)angle,
                        ssGetInputPortDimensions(S, 2),
                        ssGetInputPortNumDimensions(S, 2), sizeof(real32_T));
  gs_angle_distance_Outputs_wrapper(sc_pos_vec_ecef_t, gnd_stn_pos_vec_ecef_t,
    angle_t, distance_t);
  NDTransposeByDstSpecs((void*)distance, (const void*)distance_t,
                        ssGetOutputPortDimensions(S, 0),
                        ssGetOutputPortNumDimensions(S, 0), sizeof(real32_T));
}

/* Function: mdlTerminate =====================================================
 * Abstract:
 *    In this function, you should perform any actions that are necessary
 *    at the termination of a simulation.  For example, if memory was
 *    allocated in mdlStart, this is the place to free it.
 */
static void mdlTerminate(SimStruct *S)
{
}

#ifdef MATLAB_MEX_FILE                 /* Is this file being compiled as a MEX-file? */
#include "simulink.c"                  /* MEX-file interface mechanism */
#else
#include "cg_sfun.h"                   /* Code generation registration function */
#endif
